spring:
  jpa:
    show-sql: false
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3306/helper?useSSL=false&serverTimezone=Hongkong&characterEncoding=utf-8
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 111
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
server:
  port: 8848


jwt:
  secret: 6FRiKtvF9zTq3kdzvis6RyWXJDvnYHPs
  expireTime: 720
config:
  debug: false

